# Making a OOP MultiClass Classification Neuronal Network

- The purpose of this notebook is to code a MultiClass Classification Artificial Neuronal Network with a semi-professionnal workflow.
- The second objective is to practice OOP
- And finally, it is also done to practice doscstring and commentaries

In [1]:
# Importation of usefull librairies

import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Creation of layer class

class layer():
    """ Create a Neuronal layer """
    
    def __init__(self):
        self.input = None
        self.output = None
    
    # Compute output Y of a layer for a given input
    def forward(self, input):
        raise NotImplementedError
    
    # Compute dE/dX for a given dE/dY and update parameters
    def backward(self, output_error, learning_rate):
        raise NotImplementedError
        
layer_test = layer()

print(layer_test.input)
print(layer_test.output)
print(layer_test.forward('test'))
print(layer_test.backward('test', 'test'))

None
None


NotImplementedError: 

In [8]:
# Making of a class FullyConnectedLayer

class FClayer(layer):
    """ Create a fully connected layer that heritate from layer """
    
    def __init__(self, input_size, output_size):
        # Weight et bias initiliazisation
        self.W = np.random.randn(output_size, input_size)
        self.b = np.random.randn(output_size, 1)
        
    def forward_propagation(self):
        raise NotImplementedError
        
    def backward_propagation(self):
        raise NotImplementedError
        
test_fclayer = FClayer(4, 2)

print(test_fclayer.W.shape)
print(test_fclayer.b.shape)
print(test_fclayer.W[:2])
print(test_fclayer.b[:2])

(2, 4)
(2, 1)
[[-0.69685892  2.04389869  1.93254145 -1.68370048]
 [-0.01388672 -1.11722552  0.41889614 -0.85731101]]
[[ 0.31066722]
 [-1.50146341]]
